### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by pugovic** [dxpr/lightning_dxpr#10]
While installing the dxpr_lightning with  demo  logistics content,client  gets:

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: /core/install.php?rewrite=ok&profile=lightning_dxpr&langcode=en&id=2&op=do_nojs&op=do StatusText: OK ResponseText: Symfony\Component\Serializer\Exception\UnexpectedValueException: Type http://drupal.org/rest/type/block_content/drag_and_drop_block does not correspond to an entity on this site. in Drupal\hal\Normalizer\ContentEntityNormalizer->getTypedDataIds() (line 281 of /var/www/dxpr-demo.nfi-llc.com/web/docroot/core/modules/hal/src/Normalizer/ContentEntityNormalizer.php).

So 
When I have done the installation for the 2.x branch I got this error 
![M5gTBId 1](https://user-images.githubusercontent.com/12621645/91303707-107bd500-e7b1-11ea-8315-9ac3c2e8f08d.png)

but 
when  I have done the installation for the 1.x branch I got this error do 
![HdWBRs8 1](https://user-images.githubusercontent.com/12621645/91303678-05c14000-e7b1-11ea-9ec7-4a14b86a43eb.png)
(like client has shown to us)

related task https://dxpr.monday.com/boards/454831816/pulses/690729079

So it is needed to be fixed

**Comment by pugovic** [comment]
@jjroelofs  When installing the dxpr_lightning profile

for branch 2.x received such error https://i.imgur.com/M5gTBId.png

for branch 1.x received this error https://i.imgur.com/HdWBRs8.png

For testing, the project was used https://github.com/dxpr/lightning_dxpr_project

For the 2.x (8) branch, everything was quite simple, there was simply no dxpr_gridstack module dependency in the composer.json file
which is used in the dxpr_logistics_demo child module. After adding the dependency, the error disappeared.
4+ installations was passed , because each error in profile case required repeating the installation again.


For the 1.x (9) branch, the core code was examined and it turned out that optional configs of  module  are installed at the end of the profile installation. docroot / core / lib / Drupal / Core / Config / ConfigInstaller.php https://i.imgur.com/hxeLtAC.png

https://i.imgur.com/VgeRbAX.png
 
Installed 5 times,
 
 I also want to note that in d9 the profile tasks (which appear at the end of the profile installation) are not considered to be the profile installation, therefore the module configurations were imported in a normal order and there was no such error docroot / core / lib / Drupal / Core / Config / ConfigInstaller.php Differs from d8 https://i.imgur.com/Imd2Fc3.png

**Comment by jjroelofs** [comment]
@pugovic I think this is already fixed, can you still reproduce it? with the latest Lightning DXPR code? Maybe the client has an old installation with old code.

**Comment by pugovic** [comment]
@jjroelofs  This is not fixed, because the pr https://github.com/dxpr/lightning_dxpr/pull/11  waited for code review. This pr has been well tested. But if you want i will do it anyway.

**Comment by jjroelofs** [comment]
@pugovic the 1.x branch is deprecated and the 2.x branch does not depend on dxpr_gridstack anymore, so I think the root cause of the problem is now fixed, and we don't need these changes anymore. correct?

**Comment by pugovic** [comment]
@jjroelofs If branch 1.x is deprecated then yes the bug has already been fixed

**Comment by pugovic** [comment]
The task is already done because: the 1.x branch is deprecated and the 2.x branch does not depend on dxpr_gridstack anymore,

**Comment by pugovic** [comment]
The task is already done because: the 1.x branch is deprecated and the 2.x branch does not depend on dxpr_gridstack anymore,
