### ISSUE TITLE
The Upload destination options are missing

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/lightning_dxpr#13]
From client:

To do this on dxpr demo.

Create a custom block:
Home > Administration > Structure > Block layout Custom block library +Add custom block type
Add Field
Choose either: (Reference) File, (Reference)Image > Add label > Save and continue
The Upload destination options are missing. It's a required field without an illegal choice warning. You can't save or make changes. You can back out bot not change the field settings.

Note: The older version of Glazed with a different administration theme also does this. An older version of the default (on Drupal 8.7.7) lightening works fine. I can't find any issues like this on drupal.org. I'm not sure what to do.

![custom-block-field-illegal-choice (1)](https://user-images.githubusercontent.com/904576/102973929-eedfef80-44fd-11eb-9069-286aaca7cf0c.png)

@dench0 if you need more info please ask the client directly in the ticket system: https://app.dxpr.com/hc/tickets/4178/custom-block-file-field-image-field-missing-upload-destination-option

**Comment by dench0** [comment]
@jjroelofs 
You can close this issue because it related to the dxpr_builder: https://github.com/dxpr/dxpr_builder/issues/311
