### ISSUE TITLE
Fix default_content 9.2.0 problem and any other 9.2.0 compatibility issues

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/lightning_dxpr#29]
When installing this distro we fail with the following message:

```
my_drupal9_project_qa_demo |  [info] dxpr_qa_demo module installed.
my_drupal9_project_qa_demo |
my_drupal9_project_qa_demo | In ContainerBuilder.php line 1032:
my_drupal9_project_qa_demo |
my_drupal9_project_qa_demo |   [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
my_drupal9_project_qa_demo |   You have requested a non-existent service "default_content.importer".
my_drupal9_project_qa_demo |
my_drupal9_project_qa_demo |
```

It's happening since today so I'm guessing it's due to Drupal 9.2.0 release.

Can you look into this and suggest/implement a fix, workaround, or patch for contrib projects.

**Comment by dench0** [comment]
I can reproduce it: neither by drush command (
![2021-06-17_19-53](https://user-images.githubusercontent.com/3121558/122441001-c8c77380-cfa5-11eb-8beb-c1ffb0ce0391.png)
) nor by a regular installation with using the browser.

**Comment by jjroelofs** [comment]
@dench0  I also cannot reproduce the problem locally but unfortunately we do have the problem on try.dxpr.com, the site is installed with most of the modules and all demo content missing: https://try.dxpr.com/1624161944/docroot/user/1

We have a Docker image that you can use to reproduce the problem, I will send you a link to its documentation after I verify the documentation works correctly.

**Comment by jjroelofs** [comment]
@dench0 You can reproduce the error by following the steps here:
https://app.dxpr.com/documentation/internal/continuous-integration-continuous-development

I can also reproduce the error when running the installation on try.dxpr.com.
On try.dxpr.com we run PHP 8.0 but on my local environment installation works fine with both PHP 7.3 and 8.0. What environment did you use when you failed to reproduce the error?

**Comment by jjroelofs** [comment]
@dench0 can you please look into this again? it turns out that my fix was not a fix at all. For some reason after editing the default_content module's info file the site install process was working again, but later I could not repeat this success.

It's very strange, and as a temporary workaround I downgraded lightning_dxpr to use lightning 5.1.x which requires Drupal 9.1.x...

But I would still like to see this fixed, can you please try to reproduce it on a Ubuntu box? if you can't reproduce it yourself I can give you can reproduce it on the try2.dxpr.com server where we experienced this problem for sure.

We started seeing this problem when Drupal 9.2.0 came around, but it's strange that I cannot find any reports of people experiencing similar problems. That's why my suspicion is that Acquia's big core patch might be the culprit. As you can see from my comment they were getting sloppy with their patch in the release process as well:

https://www.drupal.org/project/lightning/issues/3143958#comment-14125487

So I suspect the coding also might have gotten sloppy, especially since they are deprecating lightning. Unfortunately we can't simply ignore the core patch because Lightning's installation code depends on it.

Other causes I already explored:
- PHP memory limit and execution time settings
- File permissions issues (setting everything to 777 doesn't help)
- UTF-8 BOM and newline issues
- 
.. there must be something else going on.

**Comment by dench0** [comment]
I see that now in the requirements is  `acquia/lightning 5.1.8` (https://i.imgur.com/pLjzy59.png), but how I understood the problem with the `5.2.0`,  so how I should test now?

> But I would still like to see this fixed, can you please try to reproduce it on a Ubuntu box?

On my local machine, I'm using `Docker4Drupal` (https://wodby.com/docs/1.0/stacks/drupal/local/)

**Comment by jjroelofs** [comment]
outdated
