### ISSUE TITLE
auto update to packagist

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/lightning_dxpr#3]
link provided by packagist: https://packagist.org/about#how-to-update-packages

**Comment by hoatle** [comment]
@jjroelofs could you send me the api token? https://packagist.org/profile/

**Comment by hoatle** [comment]
done:
- https://packagist.org/packages/dxpr/lightning-dxpr-project
- https://packagist.org/packages/dxpr/lightning_dxpr
