### ISSUE TITLE
Asset-packagist is defunct and causing builds to fail

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/lightning_dxpr#45]
Related:

* https://github.com/hiqdev/asset-packagist/issues/146
* https://github.com/dxpr/dxpr_builder/issues/874
* https://ryanszrama.com/blog/04-18-2022/replace-asset-packagist-custom-package-repositories
* https://www.drupal.org/project/lightning_media/issues/3275867
* https://www.drupal.org/project/lightning_media/issues/3275871

Solution: increment version number of dxpr/lightning dependency which will depend on a patched version of lightning_media

**Comment by SilverFire** [comment]
Asset-packagist is up, sorry for the troubles. You can find an explanation in the original issue: https://github.com/hiqdev/asset-packagist/issues/146#issuecomment-1106742011

**Comment by jjroelofs** [comment]
Hi SilverFird, thanks for the update! Glad to hear you are safe and the service lives on.
