### ISSUE TITLE
Create 2.x branch that depends on Drupal 9

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/lightning_dxpr#9]
On june 3rd Acquia Lightning released 5.0.0-beta2, it's probably stable enough to start developing our 2.x branch on for testing. 
Bootstrap basetheme seems to be a bit problematic, I hope it's fixed before the weekend:
https://www.drupal.org/project/bootstrap/issues/3096963#comment-13664874

**Comment by jjroelofs** [comment]
@dench0 for me composer update to lightning 5.x is not working and also very slow. if you also have problems, better to just download a tarball: https://github.com/acquia/lightning/releases

**Comment by jjroelofs** [comment]
now that we have D9 compatibility please proceed with this task @dench0 
If you find any leftover D9 related issues pls create a github/d.o. issue in the corresponding project and link it from this thread.

**Comment by dench0** [comment]
@jjroelofs Here the branches:
https://github.com/dxpr/lightning_dxpr/tree/2.x
https://github.com/dxpr/lightning_dxpr_project/tree/2.x
Now there are two modules which does not allow to install it: `tokenuuid` and `dxpr_gridstack`, because they have only drupal 8 in core requirements.
They both have issues on d.o with patches:
https://www.drupal.org/project/dxpr_gridstack/issues/3144694
https://www.drupal.org/project/tokenuuid/issues/3149093

**Comment by jjroelofs** [comment]
@dench0 can you test and post a review to both the patches you linked?

**Comment by dench0** [comment]
@jjroelofs there is nothing to test, that patches just add one line to the info.yml file for the supporting the d9:
```
core_version_requirement: ^8.7.7 || ^9
```
The problem is, while that patches not applied and released, composer does not allow to install that modules due to version conflict.

**Comment by jjroelofs** [comment]
@dench0 the policy on Drupal.org is that a patch can get committed after 2 people review it. 
When reviewing the patches, please also just update to Drupal 9 with those modules installed and verify that automated upgrade didn't miss anything.

Reviewing the patches notifies the maintainer that people are waiting for this, so it hopefully motivates them to do something.

**Comment by dench0** [comment]
@jjroelofs I reviewed `tokenuuid` and change issues status to `reviewed`.
`dxpr_gridstack` also working fine with d9, but if you apply one additional patch: https://www.drupal.org/project/dxpr_gridstack/issues/3154115#comment-13713902

**Comment by jjroelofs** [comment]
can you please continue this task and give it priority? it a module is not working in D9 just remove it for now, it's most important we will be compatible with Lightning 5 and their new media changes

**Comment by dench0** [comment]
@jjroelofs 
I removed `tokenuuid` and `dxpr_greedstack` and now it seems like installation should go without any errors, but to test further me me need access web token. 
Command to run composer installation:
```
composer create-project dxpr/lightning-dxpr-project:2.x-dev <project_dir>
```

**Comment by dench0** [comment]
@jjroelofs done.
To install you need to execute:
```
composer cc
composer create-project dxpr/lightning-dxpr-project:2.x-dev <project_dir>
```

**Comment by jjroelofs** [comment]
@dench0 can you put back gridstack, I just created a full release with the 9.x patches

**Comment by jjroelofs** [comment]
@dench0 token_uuid also released with 9.x patch so you can add it back too

**Comment by jjroelofs** [comment]
I think actually we don't need to include token_uuid and dxpr_gridstack for now. they don't really belong in here, they are only used in our test profile
